export PATH=$PATH:/home/glitch/.local/bin
export EDITOR='vim'
export VISUAL='vim'
export TMPDIR='/home/glitch/tmp'
alias svim='sudo -E vim'
alias snvim='sudo -E nvim'
alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias pacman="yay"
