export PATH=$PATH:$HOME/.local/bin:$HOME/.cargo/bin
export EDITOR='vim'
export VISUAL='vim'
export TMPDIR='$HOME/.tmp'
export XDG_CONFIG_DIRS='/etc/xdg'
alias svim='sudo -E vim'
alias snvim='sudo -E nvim'
alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
