#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill polybar 2>/dev/null
pkill firefox 2>/dev/null
pkill kitty 2>/dev/null

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#aa0000"
bspc config normal_border_color "#330000"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar bar1 &
setxkbmap -layout "gb"
xsetroot -cursor_name left_ptr

# autostart
~/.config/bspwm/autostart &
